### ISSUE TITLE
Doesn't work on Java9 and macOS

### ISSUE THREAD

**Issue by argius** [argius/Stew5#5]
The following error occurred when running with GUI mode on Java9 and macOS.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/AboutHandler
	at stew5.ui.swing.WindowLauncher.<init>(WindowLauncher.java:72)
	at stew5.ui.swing.WindowLauncher.main(WindowLauncher.java:887)
	at stew5.App.run(App.java:110)
	at stew5.App.main(App.java:133)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 4 more
```

Environment:
```
JRE : Java(TM) SE Runtime Environment 9+181
OS : Mac OS X (osver=10.12.6)
Locale : ja_JP
```

**Comment by argius** [comment]
I'm trying to solve with JavaScript.
